training:
  name: 'cloud_train_lightning'
  use_wandb: True 
  data_path: '/datasets/voxceleb2/voxceleb2_AV/dev/mp4/'  
  learning_rate: 0.000001
  num_epochs: 100
  batch_size: 16 
  epochs_per_stage: 10 
  transition_epochs: 5
  initial_resolution: 16
  final_resolution: 256

weights:
  irfd:
    i: 0.0001
    e: 0.0001
    p: 0.0001
  gan:
    real: 0.2
    fake: 0.6
    feature_matching: 0.2
    adversarial: 0.4
  perceptual:
    lpips: 0.5
    vgg: 0.5
