training:
  name: 'gans_gen_test_2'
  data_path: 'dataset/mp4'
  learning_rate: 0.001
  num_epochs: 10
  batch_size: 12

weights:
  gan:
    real: 0.2
    fake: 0.4
    feature_matching: 0.2
    adversarial: 0.2
  perceptual:
    lpips: 1.0
