training:
  name: 'high_adversieral_loss'
  data_path: 'dataset/mp4'
  learning_rate: 0.0001
  num_epochs: 10
  batch_size: 12

weights:
  gan:
    real: 0.2
    fake: 0.6
    feature_matching: 0.2
    adversarial: 0.4
  perceptual:
    lpips: 1.0
