training:
  name: 'just_gan'
  data_path: 'dataset/mp4'
  learning_rate: 0.01
  num_epochs: 10
  batch_size: 8 

weights:
  vasa:
    gaze: 0
    arcface: 0
    emodel: 0
    face3d: 0
  gan:
    real: 0.2
    fake: 0.2
    feature_matching: 0.2
  perceptual:
    arcface: 0
    imagenet: 0
    gaze: 0
  cycle: 0
