training:
  name: 'just_image_net'
  data_path: 'dataset/mp4'
  learning_rate: 0.01
  num_epochs: 10
  batch_size: 16

weights:
  vasa:
    gaze: 0
    arcface: 0
    emodel: 0
    face3d: 0
  gan:
    real: 0
    fake: 0
    feature_matching: 0
  perceptual:
    arcface: 0
    imagenet: 0.2
    gaze: 0
  cycle: 0
